In [102]:
import numpy as np

In [103]:
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [104]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [105]:
np.random.randint(50,high=101,size=100)

array([ 86,  76,  62,  61,  91,  79,  78,  88,  78,  83,  80, 100,  73,
        53,  60,  72,  50,  92,  87,  67,  64,  51,  72,  65,  85,  83,
        85,  70,  88,  85,  60,  66,  74,  90,  65,  96,  90,  68,  55,
        64,  83,  82,  84,  53,  91,  53,  79,  54,  54,  75,  50,  98,
        75,  95,  65,  63,  55,  62,  90,  79,  67,  97,  53,  67,  78,
        96,  53,  99,  53,  92,  71,  63,  84,  61,  62,  80,  87,  86,
        99,  90,  93,  75,  82,  84,  82,  78,  99,  93,  86,  95,  75,
        59,  72,  87,  52,  68,  72,  51,  70,  52])

In [106]:
np.random.randint(50,high=101,size=(5,5))

array([[ 52,  74,  51,  73,  95],
       [ 74,  87,  74,  93,  74],
       [ 66,  68,  77,  69,  64],
       [ 90,  92,  96,  90,  94],
       [100,  90,  86,  70,  50]])

In [107]:
content = np.random.randint(50,high=101,size=(50,5))

In [108]:
import pandas as pd
pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])

國文   英文  數學   地理   歷史
1    63   98  53   50   64
2    71   76  66   91   52
3    60   94  75   54   94
4    82   71  53   62   66
5    90  100  91   73   60
6    73   95  94   67   75
7    85   92  78   54   93
8    64   60  72   84   98
9    78   65  59   84   51
10   60   81  67   71   75
11   98   56  82   51   88
12   99   61  83   75   64
13   53   55  82   69   71
14   61   51  55   96   75
15   86   82  98   76   71
16   97   73  65   53   59
17   60   64  77   86   75
18   66   79  76   76   63
19   65   70  77   68   75
20   64   50  84   84   87
21   64   65  52   53   96
22   62   68  59   51   78
23   97   80  65   90   79
24   62   78  74   96   93
25   72   61  72   92   65
26   89   70  80   95   77
27   61   91  52   67   52
28   98   76  50   92   99
29   73   98  69  100   76
30   93   81  55   85   78
31   79   79  75   74   79
32   79   94  82   71   79
33   82   55  60   98  100
34   65   78  75   67   64
35  100   70  95   90   50
36   95   76  84   75   74
37   79   61  90   55   89
38   96   53  83   92   97
39   61   62  55   95  100
40   90   69  90   50   92
41   59   88  60   89   59
42   73   99  70   88   70
43   67   95  59   89   92
44   86   75  79   64   70
45   70   54  73   63   93
46   70   76  60   83   93
47   70   54  77   56   64
48   69   91  64  100   99
49   99   86  69   80   81
50   75   87  52   69   58

In [109]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])

In [110]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     328
2     356
3     377
4     334
5     414
6     404
7     402
8     378
9     337
10    354
11    375
12    382
13    330
14    338
15    413
16    347
17    362
18    360
19    355
20    369
21    330
22    318
23    411
24    403
25    362
26    411
27    323
28    415
29    416
30    392
31    386
32    405
33    395
34    349
35    405
36    404
37    374
38    421
39    373
40    391
41    355
42    400
43    402
44    374
45    353
46    382
47    321
48    423
49    415
50    341
dtype: int64

In [111]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號" for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

國文   英文  數學   地理   歷史
第1號    63   98  53   50   64
第2號    71   76  66   91   52
第3號    60   94  75   54   94
第4號    82   71  53   62   66
第5號    90  100  91   73   60
第6號    73   95  94   67   75
第7號    85   92  78   54   93
第8號    64   60  72   84   98
第9號    78   65  59   84   51
第10號   60   81  67   71   75
第11號   98   56  82   51   88
第12號   99   61  83   75   64
第13號   53   55  82   69   71
第14號   61   51  55   96   75
第15號   86   82  98   76   71
第16號   97   73  65   53   59
第17號   60   64  77   86   75
第18號   66   79  76   76   63
第19號   65   70  77   68   75
第20號   64   50  84   84   87
第21號   64   65  52   53   96
第22號   62   68  59   51   78
第23號   97   80  65   90   79
第24號   62   78  74   96   93
第25號   72   61  72   92   65
第26號   89   70  80   95   77
第27號   61   91  52   67   52
第28號   98   76  50   92   99
第29號   73   98  69  100   76
第30號   93   81  55   85   78
第31號   79   79  75   74   79
第32號   79   94  82   71   79
第33號   82   55  60   98  100
第34號   65   78  75   67   64
第35號  100   70  95   90   50
第36號   95   76  84   75   74
第37號   79   61  90   55   89
第38號   96   53  83   92   97
第39號   61   62  55   95  100
第40號   90   69  90   50   92
第41號   59   88  60   89   59
第42號   73   99  70   88   70
第43號   67   95  59   89   92
第44號   86   75  79   64   70
第45號   70   54  73   63   93
第46號   70   76  60   83   93
第47號   70   54  77   56   64
第48號   69   91  64  100   99
第49號   99   86  69   80   81
第50號   75   87  52   69   58

In [112]:
df1.loc["第1號"]

國文    63
英文    98
數學    53
地理    50
歷史    64
Name: 第1號, dtype: int64

In [113]:
df1.loc["第1號",:]

國文    63
英文    98
數學    53
地理    50
歷史    64
Name: 第1號, dtype: int64

In [114]:
df1.loc[["第1號","第5號","第10號"]]

國文   英文  數學  地理  歷史
第1號   63   98  53  50  64
第5號   90  100  91  73  60
第10號  60   81  67  71  75

In [115]:
df1.iloc[:5]

國文   英文  數學  地理  歷史
第1號  63   98  53  50  64
第2號  71   76  66  91  52
第3號  60   94  75  54  94
第4號  82   71  53  62  66
第5號  90  100  91  73  60

In [116]:
df1.iloc[-5:]

國文  英文  數學   地理  歷史
第46號  70  76  60   83  93
第47號  70  54  77   56  64
第48號  69  91  64  100  99
第49號  99  86  69   80  81
第50號  75  87  52   69  58

In [117]:
df1

國文   英文  數學   地理   歷史
第1號    63   98  53   50   64
第2號    71   76  66   91   52
第3號    60   94  75   54   94
第4號    82   71  53   62   66
第5號    90  100  91   73   60
第6號    73   95  94   67   75
第7號    85   92  78   54   93
第8號    64   60  72   84   98
第9號    78   65  59   84   51
第10號   60   81  67   71   75
第11號   98   56  82   51   88
第12號   99   61  83   75   64
第13號   53   55  82   69   71
第14號   61   51  55   96   75
第15號   86   82  98   76   71
第16號   97   73  65   53   59
第17號   60   64  77   86   75
第18號   66   79  76   76   63
第19號   65   70  77   68   75
第20號   64   50  84   84   87
第21號   64   65  52   53   96
第22號   62   68  59   51   78
第23號   97   80  65   90   79
第24號   62   78  74   96   93
第25號   72   61  72   92   65
第26號   89   70  80   95   77
第27號   61   91  52   67   52
第28號   98   76  50   92   99
第29號   73   98  69  100   76
第30號   93   81  55   85   78
第31號   79   79  75   74   79
第32號   79   94  82   71   79
第33號   82   55  60   98  100
第34號   65   78  75   67   64
第35號  100   70  95   90   50
第36號   95   76  84   75   74
第37號   79   61  90   55   89
第38號   96   53  83   92   97
第39號   61   62  55   95  100
第40號   90   69  90   50   92
第41號   59   88  60   89   59
第42號   73   99  70   88   70
第43號   67   95  59   89   92
第44號   86   75  79   64   70
第45號   70   54  73   63   93
第46號   70   76  60   83   93
第47號   70   54  77   56   64
第48號   69   91  64  100   99
第49號   99   86  69   80   81
第50號   75   87  52   69   58

In [118]:
df1.loc['第10號':'第15號']

國文  英文  數學  地理  歷史
第10號  60  81  67  71  75
第11號  98  56  82  51  88
第12號  99  61  83  75  64
第13號  53  55  82  69  71
第14號  61  51  55  96  75
第15號  86  82  98  76  71

In [119]:
df1

國文   英文  數學   地理   歷史
第1號    63   98  53   50   64
第2號    71   76  66   91   52
第3號    60   94  75   54   94
第4號    82   71  53   62   66
第5號    90  100  91   73   60
第6號    73   95  94   67   75
第7號    85   92  78   54   93
第8號    64   60  72   84   98
第9號    78   65  59   84   51
第10號   60   81  67   71   75
第11號   98   56  82   51   88
第12號   99   61  83   75   64
第13號   53   55  82   69   71
第14號   61   51  55   96   75
第15號   86   82  98   76   71
第16號   97   73  65   53   59
第17號   60   64  77   86   75
第18號   66   79  76   76   63
第19號   65   70  77   68   75
第20號   64   50  84   84   87
第21號   64   65  52   53   96
第22號   62   68  59   51   78
第23號   97   80  65   90   79
第24號   62   78  74   96   93
第25號   72   61  72   92   65
第26號   89   70  80   95   77
第27號   61   91  52   67   52
第28號   98   76  50   92   99
第29號   73   98  69  100   76
第30號   93   81  55   85   78
第31號   79   79  75   74   79
第32號   79   94  82   71   79
第33號   82   55  60   98  100
第34號   65   78  75   67   64
第35號  100   70  95   90   50
第36號   95   76  84   75   74
第37號   79   61  90   55   89
第38號   96   53  83   92   97
第39號   61   62  55   95  100
第40號   90   69  90   50   92
第41號   59   88  60   89   59
第42號   73   99  70   88   70
第43號   67   95  59   89   92
第44號   86   75  79   64   70
第45號   70   54  73   63   93
第46號   70   76  60   83   93
第47號   70   54  77   56   64
第48號   69   91  64  100   99
第49號   99   86  69   80   81
第50號   75   87  52   69   58

In [120]:
df1.sum(axis=1)
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean

In [121]:
df1

國文   英文  數學   地理   歷史   總分    平均
第1號    63   98  53   50   64  328  65.6
第2號    71   76  66   91   52  356  71.2
第3號    60   94  75   54   94  377  75.4
第4號    82   71  53   62   66  334  66.8
第5號    90  100  91   73   60  414  82.8
第6號    73   95  94   67   75  404  80.8
第7號    85   92  78   54   93  402  80.4
第8號    64   60  72   84   98  378  75.6
第9號    78   65  59   84   51  337  67.4
第10號   60   81  67   71   75  354  70.8
第11號   98   56  82   51   88  375  75.0
第12號   99   61  83   75   64  382  76.4
第13號   53   55  82   69   71  330  66.0
第14號   61   51  55   96   75  338  67.6
第15號   86   82  98   76   71  413  82.6
第16號   97   73  65   53   59  347  69.4
第17號   60   64  77   86   75  362  72.4
第18號   66   79  76   76   63  360  72.0
第19號   65   70  77   68   75  355  71.0
第20號   64   50  84   84   87  369  73.8
第21號   64   65  52   53   96  330  66.0
第22號   62   68  59   51   78  318  63.6
第23號   97   80  65   90   79  411  82.2
第24號   62   78  74   96   93  403  80.6
第25號   72   61  72   92   65  362  72.4
第26號   89   70  80   95   77  411  82.2
第27號   61   91  52   67   52  323  64.6
第28號   98   76  50   92   99  415  83.0
第29號   73   98  69  100   76  416  83.2
第30號   93   81  55   85   78  392  78.4
第31號   79   79  75   74   79  386  77.2
第32號   79   94  82   71   79  405  81.0
第33號   82   55  60   98  100  395  79.0
第34號   65   78  75   67   64  349  69.8
第35號  100   70  95   90   50  405  81.0
第36號   95   76  84   75   74  404  80.8
第37號   79   61  90   55   89  374  74.8
第38號   96   53  83   92   97  421  84.2
第39號   61   62  55   95  100  373  74.6
第40號   90   69  90   50   92  391  78.2
第41號   59   88  60   89   59  355  71.0
第42號   73   99  70   88   70  400  80.0
第43號   67   95  59   89   92  402  80.4
第44號   86   75  79   64   70  374  74.8
第45號   70   54  73   63   93  353  70.6
第46號   70   76  60   83   93  382  76.4
第47號   70   54  77   56   64  321  64.2
第48號   69   91  64  100   99  423  84.6
第49號   99   86  69   80   81  415  83.0
第50號   75   87  52   69   58  341  68.2

In [122]:
df2 = df1.sort_values(by='總分',ascending=False)

In [123]:
df2.iloc[:5]

國文  英文  數學   地理  歷史   總分    平均
第48號  69  91  64  100  99  423  84.6
第38號  96  53  83   92  97  421  84.2
第29號  73  98  69  100  76  416  83.2
第28號  98  76  50   92  99  415  83.0
第49號  99  86  69   80  81  415  83.0

In [124]:
df2.iloc[-5:]

國文  英文  數學  地理  歷史   總分    平均
第13號  53  55  82  69  71  330  66.0
第1號   63  98  53  50  64  328  65.6
第27號  61  91  52  67  52  323  64.6
第47號  70  54  77  56  64  321  64.2
第22號  62  68  59  51  78  318  63.6

In [128]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False)
df2

國文   英文  數學   地理   歷史   總分    平均    排名
第48號   69   91  64  100   99  423  84.6   1.0
第38號   96   53  83   92   97  421  84.2   2.0
第29號   73   98  69  100   76  416  83.2   3.0
第28號   98   76  50   92   99  415  83.0   4.0
第49號   99   86  69   80   81  415  83.0   5.0
第5號    90  100  91   73   60  414  82.8   6.0
第15號   86   82  98   76   71  413  82.6   7.0
第26號   89   70  80   95   77  411  82.2   9.0
第23號   97   80  65   90   79  411  82.2   8.0
第32號   79   94  82   71   79  405  81.0  10.0
第35號  100   70  95   90   50  405  81.0  11.0
第6號    73   95  94   67   75  404  80.8  12.0
第36號   95   76  84   75   74  404  80.8  13.0
第24號   62   78  74   96   93  403  80.6  14.0
第43號   67   95  59   89   92  402  80.4  16.0
第7號    85   92  78   54   93  402  80.4  15.0
第42號   73   99  70   88   70  400  80.0  17.0
第33號   82   55  60   98  100  395  79.0  18.0
第30號   93   81  55   85   78  392  78.4  19.0
第40號   90   69  90   50   92  391  78.2  20.0
第31號   79   79  75   74   79  386  77.2  21.0
第46號   70   76  60   83   93  382  76.4  23.0
第12號   99   61  83   75   64  382  76.4  22.0
第8號    64   60  72   84   98  378  75.6  24.0
第3號    60   94  75   54   94  377  75.4  25.0
第11號   98   56  82   51   88  375  75.0  26.0
第37號   79   61  90   55   89  374  74.8  27.0
第44號   86   75  79   64   70  374  74.8  28.0
第39號   61   62  55   95  100  373  74.6  29.0
第20號   64   50  84   84   87  369  73.8  30.0
第25號   72   61  72   92   65  362  72.4  32.0
第17號   60   64  77   86   75  362  72.4  31.0
第18號   66   79  76   76   63  360  72.0  33.0
第2號    71   76  66   91   52  356  71.2  34.0
第41號   59   88  60   89   59  355  71.0  36.0
第19號   65   70  77   68   75  355  71.0  35.0
第10號   60   81  67   71   75  354  70.8  37.0
第45號   70   54  73   63   93  353  70.6  38.0
第34號   65   78  75   67   64  349  69.8  39.0
第16號   97   73  65   53   59  347  69.4  40.0
第50號   75   87  52   69   58  341  68.2  41.0
第14號   61   51  55   96   75  338  67.6  42.0
第9號    78   65  59   84   51  337  67.4  43.0
第4號    82   71  53   62   66  334  66.8  44.0
第21號   64   65  52   53   96  330  66.0  46.0
第13號   53   55  82   69   71  330  66.0  45.0
第1號    63   98  53   50   64  328  65.6  47.0
第27號   61   91  52   67   52  323  64.6  48.0
第47號   70   54  77   56   64  321  64.2  49.0
第22號   62   68  59   51   78  318  63.6  50.0